{"files":[{"patch":"@@ -27,1 +27,1 @@\n- * @summary Verify cause handling of SocketException\n+ * @summary Verify cause and message handling of SocketException\n@@ -30,0 +30,1 @@\n+import java.util.Objects;\n@@ -33,1 +34,1 @@\n-        String reason = \"reason\";\n+        String message = \"message\";\n@@ -36,1 +37,2 @@\n-        testException(new SocketException(cause), cause);\n+        testException(new SocketException(cause), cause.toString(), cause);\n+        testException(new SocketException(message, cause), message, cause);\n@@ -40,0 +42,1 @@\n+                                      String expectedMessage,\n@@ -41,0 +44,5 @@\n+        var message = se.getMessage();\n+        if (!Objects.equals(message, expectedMessage)) {\n+            throw new RuntimeException(\"Unexpected message \" + message);\n+        }\n+\n","filename":"test\/jdk\/java\/net\/SocketException\/TestSocketExceptionCtor.java","additions":11,"deletions":3,"binary":false,"changes":14,"status":"modified"}]}